version: '3'
services:
  mysql_5.7:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - 32769:3306
    restart: always
  
  mongo_db:
    image: mongo
    ports:
      - 27017:27017
    restart: always